name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install module
        run: pip install --editable .[dev]

      - name: Run tests
        run: pytest

      - name: Test CLI
        run: |
          echo "stdin with … no issues!" | typography
          echo "file that hasn’t got any issues!" > ./a.txt
          echo "not this one—not today!" > ./b.txt
          typography ./a.txt ./b.txt
